apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-demo-app
  namespace: cost-baseline
  labels:
    app: spot-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spot-demo-app
  template:
    metadata:
      labels:
        app: spot-demo-app
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: eks.amazonaws.com/capacityType
                    operator: In
                    values:
                      - SPOT
      containers:
        - name: app
          image: nginx:1.27-alpine
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spot-demo-service
  namespace: cost-baseline
spec:
  selector:
    app: spot-demo-app
  ports:
    - port: 80
      targetPort: 80
